### PR TITLE
Chore code cleanup 11

### PR DESCRIPTION
**Pull request by aykayen**
This PR is for the manual cleanup portion of https://github.com/FormidableLabs/recipes-flux/issues/11
- fixes idiomatic js comments
- adds newline at ends of files
- adds and removes lines for readability
- removes jshint
- adds eslint
- fixes all eslint issues

### CODE REVIEW

**Comment by ryan-roemer** [comment]
@aykayen -- Approved. Thanks!

**Comment by aykayen** [comment]
@ryan-roemer opened this PR before i saw the eslint stuff so i just decided to add it all to this branch -- changes pushed, ready for re-review

**Comment by ryan-roemer** [comment]
@aykayen -- LGTM again!

Can you in your next PR (or this one) remove that TODO list and convert to real GH issues?

**Comment by aykayen** [comment]
@ryan-roemer yep! i'll do that in my next PR

**Pull request merged**
